# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 707a6f831abfd3a58effef5eb3a382ec3d4020d98687af6f019ca23592456ca46650ad407e6bf6cabd235590449b7bc9fe9e9ab044a78ea81c5766916e64cc06

test:
  secret_key_base: b82ad8bf2cf1170eed47102b3c9bb3d564fb623bfcc09c8d354fd2f12fb3a97b8718fedf172b0cbc9bf53a8cd83f34240efe4986133cd804323a8527566793d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
